/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class EduCmds {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EduCmds(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EduCmds obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        touchvgJNI.delete_EduCmds(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void registerCmds(GiCoreView coreView) {
    touchvgJNI.EduCmds_registerCmds(GiCoreView.getCPtr(coreView), coreView);
  }

  public static int getDimensions(GiCoreView coreView, Floats vars, Chars types) {
    return touchvgJNI.EduCmds_getDimensions(GiCoreView.getCPtr(coreView), coreView, Floats.getCPtr(vars), vars, Chars.getCPtr(types), types);
  }

  public EduCmds() {
    this(touchvgJNI.new_EduCmds(), true);
  }

}
