/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class GiViewFactory {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GiViewFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GiViewFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        touchvgJNI.delete_GiViewFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static GiCoreView createView(int type) {
    long cPtr = touchvgJNI.GiViewFactory_createView(type);
    return (cPtr == 0) ? null : new GiCoreView(cPtr, false);
  }

  public static void setScreenDpi(int dpi) {
    touchvgJNI.GiViewFactory_setScreenDpi(dpi);
  }

  public GiViewFactory() {
    this(touchvgJNI.new_GiViewFactory(), true);
  }

}
