/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class GiView {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GiView(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GiView obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        touchvgJNI.delete_GiView(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    touchvgJNI.GiView_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    touchvgJNI.GiView_change_ownership(this, swigCPtr, true);
  }

  public void regenAll() {
    touchvgJNI.GiView_regenAll(swigCPtr, this);
  }

  public void regenAfterAddShape() {
    touchvgJNI.GiView_regenAfterAddShape(swigCPtr, this);
  }

  public void redraw() {
    touchvgJNI.GiView_redraw(swigCPtr, this);
  }

  public GiView() {
    this(touchvgJNI.new_GiView(), true);
    touchvgJNI.GiView_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
