/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace touchvg.core {

using System;
using System.Runtime.InteropServices;

public class Ints : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Ints(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Ints obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Ints() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          touchvgcsPINVOKE.delete_Ints(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Ints(int n) : this(touchvgcsPINVOKE.new_Ints(n), true) {
  }

  public int count() {
    int ret = touchvgcsPINVOKE.Ints_count(swigCPtr);
    return ret;
  }

  public int get(int index) {
    int ret = touchvgcsPINVOKE.Ints_get(swigCPtr, index);
    return ret;
  }

  public void set(int index, int value) {
    touchvgcsPINVOKE.Ints_set(swigCPtr, index, value);
  }

}

}
