/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace touchvg.core {

using System;
using System.Runtime.InteropServices;

public class GiCoreView : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GiCoreView(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GiCoreView obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GiCoreView() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          touchvgcsPINVOKE.delete_GiCoreView(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public GiCoreView(GiCoreView mainView) : this(touchvgcsPINVOKE.new_GiCoreView(GiCoreView.getCPtr(mainView)), true) {
  }

  public void createView(GiView view, int type) {
    touchvgcsPINVOKE.GiCoreView_createView__SWIG_0(swigCPtr, GiView.getCPtr(view), type);
  }

  public void createView(GiView view) {
    touchvgcsPINVOKE.GiCoreView_createView__SWIG_1(swigCPtr, GiView.getCPtr(view));
  }

  public void createMagnifierView(GiView newview, GiView mainView) {
    touchvgcsPINVOKE.GiCoreView_createMagnifierView(swigCPtr, GiView.getCPtr(newview), GiView.getCPtr(mainView));
  }

  public void destoryView(GiView view) {
    touchvgcsPINVOKE.GiCoreView_destoryView(swigCPtr, GiView.getCPtr(view));
  }

  public int drawAll(GiView view, GiCanvas canvas) {
    int ret = touchvgcsPINVOKE.GiCoreView_drawAll(swigCPtr, GiView.getCPtr(view), GiCanvas.getCPtr(canvas));
    return ret;
  }

  public bool drawAppend(GiView view, GiCanvas canvas) {
    bool ret = touchvgcsPINVOKE.GiCoreView_drawAppend(swigCPtr, GiView.getCPtr(view), GiCanvas.getCPtr(canvas));
    return ret;
  }

  public void dynDraw(GiView view, GiCanvas canvas) {
    touchvgcsPINVOKE.GiCoreView_dynDraw(swigCPtr, GiView.getCPtr(view), GiCanvas.getCPtr(canvas));
  }

  public int setBkColor(GiView view, int argb) {
    int ret = touchvgcsPINVOKE.GiCoreView_setBkColor(swigCPtr, GiView.getCPtr(view), argb);
    return ret;
  }

  public static void setScreenDpi(int dpi) {
    touchvgcsPINVOKE.GiCoreView_setScreenDpi(dpi);
  }

  public void onSize(GiView view, int w, int h) {
    touchvgcsPINVOKE.GiCoreView_onSize(swigCPtr, GiView.getCPtr(view), w, h);
  }

  public bool onGesture(GiView view, GiGestureType gestureType, GiGestureState gestureState, float x, float y, bool switchGesture) {
    bool ret = touchvgcsPINVOKE.GiCoreView_onGesture__SWIG_0(swigCPtr, GiView.getCPtr(view), (int)gestureType, (int)gestureState, x, y, switchGesture);
    return ret;
  }

  public bool onGesture(GiView view, GiGestureType gestureType, GiGestureState gestureState, float x, float y) {
    bool ret = touchvgcsPINVOKE.GiCoreView_onGesture__SWIG_1(swigCPtr, GiView.getCPtr(view), (int)gestureType, (int)gestureState, x, y);
    return ret;
  }

  public bool twoFingersMove(GiView view, GiGestureState gestureState, float x1, float y1, float x2, float y2, bool switchGesture) {
    bool ret = touchvgcsPINVOKE.GiCoreView_twoFingersMove__SWIG_0(swigCPtr, GiView.getCPtr(view), (int)gestureState, x1, y1, x2, y2, switchGesture);
    return ret;
  }

  public bool twoFingersMove(GiView view, GiGestureState gestureState, float x1, float y1, float x2, float y2) {
    bool ret = touchvgcsPINVOKE.GiCoreView_twoFingersMove__SWIG_1(swigCPtr, GiView.getCPtr(view), (int)gestureState, x1, y1, x2, y2);
    return ret;
  }

  public string command() {
    string ret = touchvgcsPINVOKE.GiCoreView_command(swigCPtr);
    return ret;
  }

  public bool setCommand(GiView view, string name) {
    bool ret = touchvgcsPINVOKE.GiCoreView_setCommand(swigCPtr, GiView.getCPtr(view), name);
    return ret;
  }

  public void clearCachedData() {
    touchvgcsPINVOKE.GiCoreView_clearCachedData(swigCPtr);
  }

  public int addShapesForTest() {
    int ret = touchvgcsPINVOKE.GiCoreView_addShapesForTest(swigCPtr);
    return ret;
  }

  public int getShapeCount() {
    int ret = touchvgcsPINVOKE.GiCoreView_getShapeCount(swigCPtr);
    return ret;
  }

  public bool loadFromFile(string vgfile) {
    bool ret = touchvgcsPINVOKE.GiCoreView_loadFromFile(swigCPtr, vgfile);
    return ret;
  }

  public bool saveToFile(string vgfile, bool pretty) {
    bool ret = touchvgcsPINVOKE.GiCoreView_saveToFile__SWIG_0(swigCPtr, vgfile, pretty);
    return ret;
  }

  public bool saveToFile(string vgfile) {
    bool ret = touchvgcsPINVOKE.GiCoreView_saveToFile__SWIG_1(swigCPtr, vgfile);
    return ret;
  }

  public string getContent() {
    string ret = touchvgcsPINVOKE.GiCoreView_getContent(swigCPtr);
    return ret;
  }

  public void freeContent() {
    touchvgcsPINVOKE.GiCoreView_freeContent(swigCPtr);
  }

  public bool setContent(string content) {
    bool ret = touchvgcsPINVOKE.GiCoreView_setContent(swigCPtr, content);
    return ret;
  }

  public bool loadShapes(MgStorage s) {
    bool ret = touchvgcsPINVOKE.GiCoreView_loadShapes(swigCPtr, MgStorage.getCPtr(s));
    return ret;
  }

  public bool saveShapes(MgStorage s) {
    bool ret = touchvgcsPINVOKE.GiCoreView_saveShapes(swigCPtr, MgStorage.getCPtr(s));
    return ret;
  }

  public bool zoomToExtent() {
    bool ret = touchvgcsPINVOKE.GiCoreView_zoomToExtent(swigCPtr);
    return ret;
  }

}

}
